[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"
  HUGO_VERSION = "0.55.6"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[functions]
  directory = "functions"
# https://www.youtube.com/watch?v=n_KASTN0gUE
# https://docs.netlify.com/functions/configure-and-deploy/#configure-the-functions-folder
