[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"
  HUGO_VERSION = "0.55.6"

[build]
  command = "yarn build"
  publish = "dist"
  functions = "functions" # https://www.youtube.com/watch?v=n_KASTN0gUE

[context.deploy-preview]
  command = "yarn build:preview"

# https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file


# [[redirects]]
#   from = "*"
#   to = "/"
#   status = 404

# [[redirects]]
#   from = "/*"
#   to = "/it"
#   status = 302
#   force = true
#   conditions = {Language = ["ch", "CH", "it", "IT"]}
# https://answers.netlify.com/t/redirect-by-browser-language/4849/29



[[redirects]]
  from = "/*"
  to = "/it/:splat 1"
  status = 301
#  force = true
  force = false
#  query = {path = ":path"} #  apply this rule for /old-path?path=example
  conditions = {Language = ["ch", "CH", "it", "IT"]}
  # conditions = {Country = ["ch", "CH", "it", "IT"]}



  # [[redirects]]
  #   from = "/principle"
  #   to = "/"
  #   status = 301
  #   #force = false
  #   #query = {path = ":path"}
  #
  # [[redirects]]
  #   #from = "/support"
  #   #to = "/"
  #   #status = 301
  #
  # [[redirects]]
  #   from = "/areas"
  #   to = "/"
  #   status = 301
  #
  # [[redirects]]
  #   from = "/levels"
  #   to = "/"
  #   status = 301
