[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"
  HUGO_VERSION = "0.55.6"

[build]
  command = "yarn build"
  publish = "dist"
  functions = "functions" # https://www.youtube.com/watch?v=n_KASTN0gUE

[context.deploy-preview]
  command = "yarn build:preview"

[[redirects]]
  from = "/*"
  to = "/"
  status = 404
  force = true
